### ISSUE TITLE
No code for generating starting objects

### ISSUE THREAD

**Issue by molecules** [davidsanin/Macrophage_framework#1]
Congratulations on your paper! I was so excited when I saw these two sentences "This repository contains all relevant code to reproduce the findings and figures in the associated publication. Please cite us!"

Thank you for all of your work!

I downloaded your code, but I think that you forgot to `git add` a script or two, for example the script to generate the following two objects mentioned in `Data_processing.R`:

```
data #Reference fully processed Seurat object
q.data #Fully processed query dataset Seurat object
```

And the script (or scripts) to generate the following objects mentioned in `Figures.R`:

```
pval #genes annotated with p values
tg # differentially regulated genes - pseudotime analysis with lower than 10^-9 p values
n1 # negative control dataset1 H.poly SVF
n2 # negative control dataset2 Lamina propria large intestine
n3 # negative control dataset2 L.mono SVF
markers # differentially regulated genes
lin # pseudotime analysis results
c0 #fully processed reference dataset
c1 #fully processed lamina propria dataset
c2 #fully processed sciatic nerve dataset
c3 #fully processed breast cancer dataset
c4 #fully processed artery dataset
c5 #fully processed lung dataset
c6 #fully processed liver dataset
c7 #fully processed heart dataset
c8 #fully processed retina dataset
c9 #fully processed muscle dataset
cs #fully processed skin dataset
cm #fully processed microglia dataset
c.all #fully processed integrated datasets
node_master #annotated network nodes
g_old #network
l_old #network layout
fc.umap #flow cytometry based UMAP
flow #Multidimension flow validating results
```

Thank you for your time!

**Comment by davidsanin** [comment]
Hey!

Thanks for your interest in the publication and reaching out about this.

I deposited here all the code that was "not standard" or was critical for the conclusions of our manuscript.
The functions/approach to generate most of the objects you refer to (data, q.data, n1-3, c0-9, cs and cm) are all conventional Seurat functions that are better explained by the authors. All these datasets are deposited and include count matrices that can be converted to a Seurat objects and filtered with conventional QC parameters. I used SCTransform and rpca on those data. `data` is the same as `c0` and `q.data` can be any of the query datasets that I applied the label transfer approach to.

The code to generate all other objects is actually in `Data_processing.R`"
`pval`, `tg` and `lin` are in "Pseudotime calculation"
`c.all` is in "Join all data with no supervision"
`node_master`, `g_old` and `l_old` are in "Gene expression network"
`fc.umap` and `flow` are in "Indexed data dimensionality reduction and clustering"

Hope that helps! Happy to answer any other questions you might have.
