### ISSUE TITLE
clarification on n1 and data objects in Data_processing.R

### ISSUE THREAD

**Issue by yixiangD** [davidsanin/Macrophage_framework#2]
Hi,
I have downloaded all the datasets from Genbank and am working on running your code.
Could you help me with constructing `data` and `n1` objects in Data_processing.R? How should I import the downloaded datasets to get to `data` and `n1`?
It seems `data` is a reference dataset meaning one of the datasets from a specific tissue/organ. Please let me know if I understand it correctly.
Thank you so much!

**Comment by pearcelab** [comment]
Hi
Thanks for your interest in the paper. 
The code in Data_processing.R is meant to illustrate the general approach we used to transfer labels from our reference dataset to all the other tissues and condition we studied.

`data` is the processed and clustered reference data from the adipose tissue. It is generated based on the files in GSE171328 and GSE157313. The full description of how to generate this is on our publication in the supplementary methods (https://doi.org/10.1126/sciimmunol.abl7482).

`n1` refers to any one of the 11 datasets we used in the publication to apply the transfer label approach.  Details on how we generated those are also in the supplementary methods of the study.

Hope that makes sense! If not please feel free to reach out. I can also send you the processed reference dataset.

**Comment by yixiangD** [comment]
Thank you so much for your prompt response. It would be great to have your processed reference dataset! Would you like to give me an email address for communications?

**Comment by davidsanin** [comment]
Can you email me at my contact details in the publication and we can coordinate?
