### ISSUE TITLE
how to calculate macrophage score

### ISSUE THREAD

**Issue by yixiangD** [davidsanin/Macrophage_framework#3]
Hi there,

I tried to process the raw scRNA-seq data from other papers mentioned in your paper by following your instructions.
I am confused about the following statement on calculating the macrophage score,
```Where non-macrophage cells were included in the sequencing experiment, a “Macrophage score” (table S1) was calculated, and these cells extracted, keeping at most 500 randomly selected cells per biological condition.```
Could you provide the function you used to calculate it?
Thank you!

**Comment by davidsanin** [comment]
See "AddModuleScore" in Seurat.
Cheers
